{% set name = "trame-rca" %}
{% set version = "2.3.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 287ac897f47e949b9868e0fc23917b75110d62d934b4a0d2d17c7dfa5f6ac880

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - trame-client
    - wslink
    - numpy
    - packaging
    - pillow
    - pyturbojpeg

test:
  imports:
    - trame
    - trame.modules
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/trame-rca/
  summary: Remote Controlled Area widget for trame
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - larsoner
    - banesullivan
    - jourdain
    - psavery
    - kwrobot
